### ISSUE TITLE
Error on mount

### ISSUE THREAD

**Issue by PMLS3** [scholtz/qrcode-vue3#13]
I'm using Nuxt3 and getting the following error: Uncaught (in promise) TypeError: (0 , t2.openBlock) is not a function

**Comment by MathieuBurnat** [comment]
I have the same error.

Output :
> QRCodeVue3.vue?6890:4 Uncaught (in promise) TypeError: (0 , t2.openBlock) is not a function

**Comment by garaekz** [comment]
Same

TypeError: (0 , t2.openBlock) is not a function

**Comment by Mr-hxb** [comment]
I get TypeError: (0 , s.openBlock) is not a function

**Comment by scholtz** [comment]
Same as #16
