### ISSUE TITLE
Incorrect peer dependency "vue@^2.6.0".

### ISSUE THREAD

**Issue by NaturalDevCR** [scholtz/qrcode-vue3#5]
Hi!, i just noticed that there is a warning using yarn ( i guess NPM also ).

`warning "qrcode-vue3 > @chenfengyuan/vue-qrcode@1.0.2" has incorrect peer dependency "vue@^2.6.0".`

Any corrections should be done here? 

Thanks!

**Comment by kang2019S** [comment]
I cant even npm install successful ...  I guess its the version problem.

**Comment by scholtz** [comment]
dependencies fixed
