### ISSUE TITLE
No margin prop

### ISSUE THREAD

**Issue by hasheniuk** [scholtz/qrcode-vue3#7]
There is no way to set up a `margin ` around the canvas, because the `margin` property is omitted at the `QRCodeVue3` component.

**Comment by josephshepin** [comment]
@hasheniuk  [PR #14](https://github.com/scholtz/qrcode-vue3/pull/14). Hopefully it gets merged in soon!

**Comment by JosephShepin** [comment]
this has been fixed. @scholtz you can close this issue now.

**Comment by scholtz** [comment]
@JosephShepin Merged. Thanks for PR
